# Generated by Django 4.0.4 on 2023-03-30 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Net',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('mobile_number', models.CharField(max_length=50)),
                ('account_number', models.CharField(max_length=50)),
                ('mazaya_annual', models.BooleanField(default=False)),
                ('mazaya_annual_start_date', models.DateField(blank=True, default=None, null=True)),
                ('mazaya_annual_end_date', models.DateField(blank=True, default=None, null=True)),
                ('new_account_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('actual_bill', models.CharField(max_length=50)),
                ('total_bill', models.CharField(max_length=50)),
                ('commission', models.CharField(max_length=50)),
                ('rch', models.BooleanField(default=False)),
                ('device_installments', models.BooleanField(default=False)),
                ('installments_start_date', models.DateField(blank=True, default=None, null=True)),
                ('installments_end_date', models.DateField(blank=True, default=None, null=True)),
                ('device_type', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('installments_phone_number', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('suspended', models.BooleanField(default=False)),
                ('activation_date', models.DateField()),
                ('no_ntra', models.BooleanField(default=False)),
                ('ntra_details', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('is_notes', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('lines_to_same_user', models.IntegerField(blank=True, null=True)),
                ('mr_to_account', models.BooleanField(default=False)),
                ('mr_to_corporate', models.BooleanField(default=False)),
                ('new_line', models.BooleanField(default=False)),
                ('pause', models.BooleanField(default=False)),
                ('account_manager', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.accountmanager')),
                ('net', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.net')),
                ('online_payment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.onlinepayment')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.package')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='management.provider')),
                ('special_offer', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='management.specialoffer')),
            ],
        ),
    ]
