# Generated by Django 4.1.1 on 2023-03-08 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Net",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="OnlinePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Payon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=50)),
                ("mobile_number", models.CharField(max_length=50)),
                ("account_number", models.CharField(max_length=50)),
                ("mazaya_annual", models.BooleanField()),
                ("mazaya_annual_start_date", models.DateField()),
                ("mazaya_annual_end_date", models.DateField()),
                ("mr", models.BooleanField()),
                ("new_account_number", models.CharField(max_length=50)),
                ("actual_bill", models.CharField(max_length=50)),
                ("total_bill", models.CharField(max_length=50)),
                ("commission", models.CharField(max_length=50)),
                ("rch", models.BooleanField()),
                ("device_installments", models.BooleanField()),
                ("installments_start_date", models.DateField()),
                ("installments_end_date", models.DateField()),
                ("device_type", models.CharField(max_length=50)),
                ("installments_phone_number", models.CharField(max_length=50)),
                ("pause", models.BooleanField()),
                ("suspended", models.BooleanField()),
                ("ntra", models.CharField(max_length=50)),
                ("is_notes", models.BooleanField()),
                ("notes", models.TextField()),
                (
                    "account_manager",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "net",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="management.net"
                    ),
                ),
                (
                    "online_payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.onlinepayment",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.package",
                    ),
                ),
                (
                    "pay_on",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.payon",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="management.provider",
                    ),
                ),
            ],
        ),
    ]
