# Generated by Django 4.1.1 on 2023-10-28 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("management", "0002_remove_customer_mazaya_annual_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="User",
            new_name="user",
        ),
    ]
