# Generated by Django 4.0.4 on 2023-03-09 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_accountmanager_alter_customer_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activation_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
