# Generated by Django 4.0.4 on 2023-03-25 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_specialoffer_customer_special_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ntra',
            new_name='ntra_details',
        ),
        migrations.AddField(
            model_name='customer',
            name='no_ntra',
            field=models.BooleanField(default=False),
        ),
    ]
