# Generated by Django 4.0.4 on 2023-11-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_alter_customer_important_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='important_notes',
        ),
    ]
