# Generated by Django 4.0.4 on 2024-05-14 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_customer_registration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='account_manager',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.accountmanager'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='net',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.net'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='online_payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.onlinepayment'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.package'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.provider'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='special_offer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.specialoffer'),
        ),
    ]
